### PR TITLE
made compatible with illuminate 8 and beta 16

### PR DESCRIPTION
**Pull request by luceos**
depends on https://github.com/flarum/core/pull/2576

### CODE REVIEW

**Comment by davwheat** [comment]
Core just merged this today! 🚀 

@luceos cool with you for me to merge this?

**Comment by imorland** [comment]
If possible, can this wait a little? I'm trying to track down an issue in `master` and resolve it for beta 15 first, please..

If it's a problem, then go ahead and I'll work around it tho

**Comment by davwheat** [comment]
It's ok, I'll just `dev-` even MOAAARRRR! :P

**Review by davwheat — APPROVED** [review]

**Comment by davwheat** [comment]
Ian has said I'm fine to merge this now, so this is people's final chance to scream out in objection to a merge!

**Comment by askvortsov1** [comment]
I preliminarily object to any objections.

**Comment by davwheat** [comment]
@askvortsov1 Well in that case, I guess I have no choice.

**Pull request merged**
